// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmkjeadjccrodaunahsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdta2plYWRqY2Nyb2RhdW5haHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Njk4OTMsImV4cCI6MjA2NzE0NTg5M30.bnZp1irTilBdmFhnSz49HZTINjK_EljGDUiqltvOED4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});